name       : fmt
version    : 9.1.0
release    : 7
source     :
    - https://github.com/fmtlib/fmt/releases/download/9.1.0/fmt-9.1.0.zip : cceb4cb9366e18a5742128cb3524ce5f50e88b476f1e54737a47ffdf4df4c996
license    : BSD-2-Clause
component  : programming.library
summary    : Small, safe and fast formatting C++ library
description: |
    {fmt} is an open-source formatting library for C++. It can be used as a safe and fast alternative to (s)printf and IOStreams.
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
