name       : fmt
version    : 8.0.1
release    : 6
source     :
    - https://github.com/fmtlib/fmt/archive/refs/tags/8.0.1.tar.gz : b06ca3130158c625848f3fb7418f235155a4d389b2abc3a6245fb01cb0eb1e01
license    : BSD-2-Clause
component  : programming.library
summary    : Small, safe and fast formatting C++ library
description: |
    {fmt} is an open-source formatting library for C++. It can be used as a safe and fast alternative to (s)printf and IOStreams.
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
